apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-deployment
  labels:
    app: library-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
      - name: library
        image: steve001steve/library:latest
        ports:
        - containerPort: 80
