apiVersion: v1
kind: Service
metadata:
  name: library-app-service
  labels:
    app: library-app
spec:
  type: ClusterIP
  selector:
    app: library-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
