name: library App CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build React Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build React Application
      run: npm run build

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/library:latest .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/library:latest

  deploy-minikube:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Install and Start Minikube
    - name: Install Minikube
      uses: medyagh/setup-minikube@v2
      with:
        minikube-version: 'latest'
        kubernetes-version: 'v1.26.0'

    - name: Start Minikube
      run: minikube start --driver=docker

    # Build Docker Image in Minikube's Docker Environment
    - name: Use Minikube Docker Environment
      run: eval $(minikube docker-env)

    - name: Build Docker Image for Minikube
      run: docker build -t library-app:latest .

    # Create a Namespace
    - name: Create Namespace
      run: |
        kubectl create namespace library || echo "Namespace already exists"

    # Deploy Kubernetes Manifests in the Namespace
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f kubernetes/deployment.yaml -n library
        kubectl apply -f kubernetes/service.yaml -n library

    # Verify Deployment in the Namespace
    - name: Verify Deployment
      run: |
        kubectl get pods -n library
        kubectl get services -n library
